config/routes.rb
SocialNetwork::Application.routes.draw do
 
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/news', :to => 'pages#news'
  
  match '/signin', :to => 'users#new'
  
  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end
  
  def about
    @title = "About"
  end
  
  def help
    @title = "Help"
  end
  
  def news
    @title = "News"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Sign up"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def title
    base_title = "Social Network Development"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
<nav class="round">
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Site News", news_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li><%= link_to "Help", help_path %></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<%= image_tag("logo.png", :alt => "Logo Goes Here", :class => "round") %>
<nav class="round">
<ul>
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Sign in", signin_path %></li>
</ul>
</nav>
</header>

app/views/layouts/_stylesheets.html.erb
 <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialNetwork</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>About the website</h1>
<p>
	<b>Current Actual Site Statistics:</b><br>
	Site Author: Samuel Hubbard<br>
	Site version: 0.3.4<br>
	Best viewed in: Firefox, Chrome, Safari (pretty much anything except Internet Explorer)<br>
	This site is being tested in Firefox.<br>
	<i>Current as of: 08.15.2011</i>
</p>
<p>
	<b>
		General Site Theory:
	</b><br>
	The total goal behind this website is to give you (my family) the means 
	to stay in touch and give updates through a more private means than currently 
	offered in sites like Facebook or Myspace. Because of the unique nature of 
	exclusivity the site will operate slightly differently than a public social 
	networking site. There will be no need to send friend requests. Once you are 
	a member of the website you will automatically be "friends" with all the other members. 
	The site is primarily being developed for my family. However, you can always 
	invite a friend to the website. The friend will be considered a guest and 
	will be subject to the rest of the family. It will be outlined in greater 
	detail upon the launch of the site via the Terms of Service but what this 
	really means is that I reserve the right to remove a friend's account at any 
	time for any reason. The reason will generally be that one (and it will only take 
	one) family member does not want that person to be a part of this site. The reason 
	behind this is that this site is in existence primarily for the family. Overall, 
	I am looking forward to the full launch of this website.
</p>
<p>
	<b>
		Current version (of actual site) specifications:
	</b>
	<ul>
		<li>
			The general layout for how the website will look
		</li>
		<li>User model completed</li>
		<li>Authentication</li>
		<li>Sessions (w/ a cookie)</li>
		<li>Status Updates</li>
		<li>Status Feed (or Stream... pick your poison)</li>
	</ul>
<p>
	<b>
		Version 1.0.0 (Launch) information:
	</b><br>
	This is the absolute basic functionality that I want to have to launch 
	the site relatively quickly. As soon as this version launches I will 
	begin work on version 2.
</p>
<p>
	<b>	
	Version 1.0.0 features:
	</b>
	<ul>
		<li>
			Profiles
		</li>
		<li>
			Global Status Stream <strong>[DONE]</strong>
		</li>
		<li>
			Personal Status Stream <strong>[DONE]</strong>
		</li>
		<li>
			Personal Photo Gallery
		</li>
		<li>
			The ability to comment on statuses and pictures 
		</li>
		<li>
			Private messages
		</li>
	</ul>
</p>
<p>
	<b>
		Version 2.0.0 information:
	</b><br>
	Version 2 is what I am truly envisioning this site to be. The reason that 
	these features probably won't be implemented at launch is because these 
	features are going to take quite a while to program and debug. I want 
	to get the site out there and available for your use.
</p>
<p>
	<b>
		Version 2.0.0 features:
	</b></br>
	<ul>
		<li>
			Global Chat
		</li>
		<li>
			Private Chat
		</li>
		<li>
			The ability to upload and view video
		</li>
		<li>
			Groups (Giving you the ability to filter information to specific groups of people)
		</li>
		<li>
			General upgrades to the basic site functionality (i.e. updated looks, updates to the status streams, etc)
		</li>
		<li>
			Events (i.e. birthdays, anniversaries, and possibly user created events)
		<li>
			A mobile version of the website for mobile phone browsers
		</li>
	</ul>
</p>
<p>
	<b>
		Other future considerations:
	</b>
	<ul>
		<li>
			Android App
		</li>
		<li>
			iPhone App
		</li>
		<li>
			Windows 7 Mobile App
		</li>
	</ul>
	<i>*This is extremely dependent on me being able to get the Developer SDKs. Plus, in 
	Apple's case (and possibly Microsoft's) I would also need to get the App approved by them 
	for you to be able to download and use. The SDK's can cost money as well as keeping it in their 
	App Store.</i>
</p>
<p>
	<b>
		This site is currently being developed using:
	</b>
	<ul>
		<li><b>Ruby on Rails</b> for the general site</li>
		<li><b>AJAX</b> for the more advanced features</li>
		<li><b>SQLite3</b> for the database</li>
		<li><b>Git</b> for version control</li>
		<li><b>Heroku</b> will most likely be used for deployment of the site</li>
	</ul>
</p>
<p>
	Keep in mind that the future features are not set in stone and may change 
	or completely disappear. With that being said, there may be new or different 
	ones that pop up along the way.
</p>
<p>
	This website is being developed for my family and their close friends. 
	It will be exclusive to those people.
</p>
<p>
	If you have any ideas <b>(ESPECIALLY A NAME FOR THE SITE)</b> that you would like to see implemented in the site 
	please let me know. I want to make this website as personalized to your wishes as possible.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
	I will add my contact information prior to pushing git and heroku.
</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
	I will implement a full help page upon the launch of site version 1.0.0. 
	Until then I don't really see you needing any help with the skeleton layout.
</p>

app/views/pages/home.html.erb
<h1>Family Social Network Development Site</h1>
<p>
	This website was developed to keep everyone who is interested in the site informed to the 
	progress of development on the full site. The <%= link_to "About", about_path %> page 
	will contain the version information that I am currently at on the real site as well as its 
	purposed features. The <%= link_to "Site News", news_path%> page will contain 
	all of the updates dealing with the development. Finally, if you wish to contact me 
	with any ideas or comments please let me know. I have set up a <%= link_to "Contact", contact_path %> page 
	just for that.
</p>
<p>
	<b>Website naming:</b><br>
	I am still trying to figure out what to name this website. If you have any 
	ideas please send them my way. Below are the naming requirements. 
	I will choose a name based on availability and how catchy it is.<br><br>
	<b>Website naming requirements:</b>
	<ul>
		<li>The domain name (for example: www.familysocialnetwork.com) must be available</li>
		<li>I don't want it to contain 'Hubbard' in the name. I'm sure that the Hughs, Kowalski, Sergeant, Smith, Marsden, and Hopson families (as well as others) will be using this site.</li>
		<li>The shorter the better</li>
	</ul>
<p>
	<b>Logo:</b><br>
	I plan on making a logo for the website. However, I would also like to 
	take submissions for the website logo. If you are interested in making a 
	logo please do so with the following requirements and send it my way.<br><br>
	<b>Logo requirements:</b>
	<ul>
		<li>The site name must be established first</li>
		<li>It must have a white or transparent background</li>
		<li>It must match the color scheme of the website/layout</li>
		<li>It must be more on the small side</li>
		<li>No animations</li>
	</ul>
</p>

app/views/pages/news.html.erb
<h1>Site News</h1>
<p>
	<b>08.15.2011</b><br>
	After A TON of debugging code... I have the status feed running as well 
	as the relationship model that I am attaching it to. Essentially, what 
	I have decided to do with that is allow you to choose if you want their 
	status updates in your status stream. I currently have it set up like 
	twitter where you "follow" the person. The reason why I have taken that 
	route is because there is a possibility that you may not want to read 
	someone's status updates. Either way, outside of that, there will be no 
	relationship model for the rest of the site. You will be able to go to anyone's 
	profile to view their info, status, pictures, etc...<br><br>
	Here's what I will be working on over the next couple of weeks:
	<ul>
		<li>Comments</li>
		<li>Profiles</li>
		<li>Private Messages</li>
		<li>... and slowly getting started on the daunting task of putting together a photo gallery</li>
	</ul><br><br>
	However, I think I will be taking a few days off of this. So far, I would estimate about 
	1500 lines of code have been written for this.
</p>
<p>
	<b>08.15.2011</b><br>
	<strong>Nerd Speak:</strong> I have completed the user model for the website. The 
	database is up and running with the user table. The passwords are 
	encrypted, hashed, and salted. I have set up a session manager that 
	will keep the user signed in until they physically sign out using a 
	cookie.<br><br>
	<strong>Normal People Speak:</strong> You can now sign up, sign in and sign out. You 
	will stay logged in until you click on sign out. Your password is 
	secure.<br><br>
	Next I will begin working on the status stream. After that, I think 
	I will work on user profiles.
<p>
	<b>08.14.2011:</b><br>
	I have the skeleton layout fully implemented and uploaded to the web. 
	I will be running two seperate projects during the development of the site. 
	This one will be updated as I make more and more progress on the real site. 
	You will be able to come to this website until the actual launch to get 
	updates on my progress.
</p>

app/views/users/new.html.erb
<h1>Sign in/Sign up</h1>
<p>
	This is where you will sign in to the website or sign up for the website.
</p>